FROM photon:latest

LABEL maintainer="tian.r.king@gmail.com"
LABEL author="w0x7ce"
LABEL version="v0.1"
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
COPY ./app /code/app

## Just for cn user
# RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories 
## End

# RUN apk update && \
#     apk upgrade && \
#     apk add --update ca-certificates 

# RUN apk add 'python<3.8'
# RUN apk add --no-cache  py3-pip
RUN tdnf install -y python3-3.7.5-5.ph3 python3-pip-3.7.5-5.ph3
# RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir --upgrade -r /code/requirements.txt

RUN (echo "from sentence_transformers import SentenceTransformer, util" ; \
     echo "model = SentenceTransformer('paraphrase-multilingual-mpnet-base-v2')") | python3

RUN echo "EXPOSE PORT 81 "
CMD ["uvicorn", "app.fast_test:app", "--host", "0.0.0.0", "--port", "81"]


